# Generated by Django 5.2.7 on 2025-11-26 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnocaja',
            name='total_egresos_mercadopago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='turnocaja',
            name='total_egresos_seña',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='turnocaja',
            name='total_egresos_transferencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='turnocaja',
            name='total_ingresos_mercadopago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='turnocaja',
            name='total_ingresos_seña',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='turnocaja',
            name='total_ingresos_transferencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
