# Generated by Django 5.2.7 on 2025-11-26 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_reserva_estado_pago_alter_reserva_comprobante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteLimite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email del cliente')),
                ('fecha', models.DateField(auto_now_add=True, db_index=True, verbose_name='Fecha del envío')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intentos_comprobante', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Límite de Comprobante',
                'verbose_name_plural': 'Límites de Comprobantes',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['email', 'fecha'], name='reservas_co_email_101d0a_idx')],
            },
        ),
    ]
